version: '3.8'

services:
  web:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    networks:
      - shared-network
    restart: always

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "stockbroker"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared-network
    ports:
      - "5433:5432"
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - shared-network
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
  postgres-data:

networks:
  shared-network:
